FROM oven/bun:alpine AS builder

WORKDIR /app

COPY frontend /app

RUN bun i --frozen-lockfile

ENV VITE_BACKEND_URL=/

RUN bun run build

FROM oven/bun:alpine AS config

WORKDIR /app

COPY . .

RUN bun i --frozen-lockfile

RUN bun run --cwd nginx start

FROM alpine

WORKDIR /var/www/app

COPY --from=builder /app/dist .

RUN apk add brotli nginx nginx-mod-http-brotli

COPY --from=config /app/nginx/dist/nginx.conf /etc/nginx/http.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
